package cli

// Turning a spec into something a platform will run.
//
//	sbx pack --spec sandbox.json
//
// A sandbox is normally a set of containers on a machine sbx controls. A platform-as-a-service
// gives you neither: one container, one HTTP port, no runtime to manage. So this writes the
// image that fits that shape - the workload as it was, plus sbx fronting its ports over the one
// port the platform routes - and `sbx connect` on a laptop turns that back into ordinary local
// ports.
//
// The generated image starts the base image's OWN process, read out of the image rather than
// guessed. A wrapper that invented an entrypoint would work for postgres, quietly not work for
// the next image somebody tried, and be wrong in a way that reads as "the database is broken".

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/aryanmehrotra/sbx/internal/agentbin"
	"github.com/aryanmehrotra/sbx/internal/spec"
)

// PackOptions is what `sbx pack` was asked for.
type PackOptions struct {
	Spec    string
	Service string // one service, or empty for all of them
	Out     string
	Version string // the sbx version to build into the image
	Pin     string // --version: the release to install instead of this build's own
	Inspect func(image string) (entrypoint, cmd []string, err error)
	Out2    io.Writer
}

// Pack writes a deployable directory per service.
func Pack(_ context.Context, opt PackOptions) error {
	version, err := packPin(opt.Version, opt.Pin)
	if err != nil {
		return err
	}

	s, err := spec.LoadSpec(opt.Spec)
	if err != nil {
		return err
	}

	out := opt.Out
	if out == "" {
		out = "sbx-pack"
	}

	w := opt.Out2
	if w == nil {
		w = os.Stdout
	}

	names := s.Names()

	if opt.Service != "" {
		if _, ok := s.Services[opt.Service]; !ok {
			return fmt.Errorf("no service %q in %s - it has %s",
				opt.Service, opt.Spec, strings.Join(names, ", "))
		}

		names = []string{opt.Service}
	}

	for _, name := range names {
		svc := s.Services[name]

		if svc.Image == "" {
			return fmt.Errorf("service %q builds from source rather than naming an image, which "+
				"pack cannot wrap: give it an `image` or build it yourself and pack that", name)
		}

		dir := filepath.Join(out, name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}

		entry, cmd, err := opt.Inspect(svc.Image)
		if err != nil {
			return fmt.Errorf("service %q: could not read %s to find out how it starts: %w",
				name, svc.Image, err)
		}

		start := append(append([]string{}, entry...), cmd...)
		if len(start) == 0 {
			return fmt.Errorf("service %q: %s declares no entrypoint or command, so there is "+
				"nothing for the packed image to run", name, svc.Image)
		}

		if err := writePack(dir, name, svc, start, version); err != nil {
			return err
		}

		fmt.Fprintf(w, "  %-14s %s\n", name, filepath.Join(dir, "Dockerfile"))
		fmt.Fprintf(w, "  %-14s from %s, fronting %s\n", "", svc.Image, portList(svc.Ports))
	}

	fmt.Fprintf(w, "\nEach directory is a build context for a platform that takes one container\n")
	fmt.Fprintf(w, "and one HTTP port. Deploy it with SBX_CONNECT_TOKEN set, then:\n\n")
	fmt.Fprintf(w, "  sbx connect https://<the-url-it-was-given>\n")

	return nil
}

func portList(ports []int) string {
	out := make([]string, 0, len(ports))
	for _, p := range ports {
		out = append(out, strconv.Itoa(p))
	}

	return strings.Join(out, ", ")
}

// front is the --front value: every port this service publishes, named after it.
func front(name string, ports []int) string {
	out := make([]string, 0, len(ports))

	for i, p := range ports {
		label := name
		if len(ports) > 1 {
			label = fmt.Sprintf("%s-%d", name, i)
		}

		out = append(out, fmt.Sprintf("%s=%d", label, p))
	}

	return strings.Join(out, ",")
}

func writePack(dir, name string, svc spec.Service, start []string, version string) error {
	env := make([]string, 0, len(svc.Env))
	for _, k := range sortedKeys(svc.Env) {
		env = append(env, fmt.Sprintf("ENV %s=%q", k, svc.Env[k]))
	}

	envBlock := ""
	if len(env) > 0 {
		envBlock = "\n" + strings.Join(env, "\n") + "\n"
	}

	dockerfile := fmt.Sprintf(`# Generated by sbx pack. Rebuild it rather than editing it.
#
# %[1]s as it was, plus sbx carrying %[2]s over the one HTTP port a platform gives you.
#
# Nothing publishes %[2]s. A platform routes the one port it was told about and no other, so the
# workload is reachable only through the tunnel - which is authenticated. That is a property of
# the deployment rather than of the workload: run this image yourself with -p and you have
# published it, and the tunnel is then one of two ways in.
#
# What the platform contributes: HTTPS, a hostname, and usually scale-to-zero. What it does not
# contribute is storage - a service with no volume starts empty every time its container is
# replaced, which is right for a branch's test data and wrong for anything you would miss.

%[5]s
FROM golang:1.26-alpine AS sbx
RUN go install -ldflags "-X main.version=%[3]s" github.com/aryanmehrotra/sbx@%[3]s

FROM %[1]s
COPY --from=sbx /go/bin/sbx /usr/local/bin/sbx
COPY start.sh /sbx-start.sh
%[4]s
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["/sbx-start.sh"]
`, svc.Image, portList(svc.Ports), version, envBlock, pinNote(version))

	if err := os.WriteFile(filepath.Join(dir, "Dockerfile"), []byte(dockerfile), 0o644); err != nil {
		return err
	}

	// The workload's own start line, quoted as the shell will read it.
	quoted := make([]string, 0, len(start))
	for _, a := range start {
		quoted = append(quoted, shellQuote(a))
	}

	script := fmt.Sprintf(`#!/bin/sh
# Generated by sbx pack.
#
# The workload in the background, sbx in the foreground. sbx is the foreground process because
# it is what the platform's health check and its scale-to-zero wake talk to, so its death should
# be what takes the container down.
set -eu

if [ -z "${SBX_CONNECT_TOKEN:-}" ]; then
  echo "SBX_CONNECT_TOKEN is not set - the tunnel refuses to start without one, because it" >&2
  echo "is the only thing between this container and anyone who finds its URL." >&2
  exit 1
fi

%s &

exec sbx serve --connect-addr=":${PORT}" --behind-proxy --front=%q
`, strings.Join(quoted, " "), front(name, svc.Ports))

	return os.WriteFile(filepath.Join(dir, "start.sh"), []byte(script), 0o755)
}

// packPin decides which sbx the generated image installs: --version when given, else this
// build's own version - and in both cases only a published release.
//
// The image runs `go install github.com/aryanmehrotra/sbx@VERSION`, which fetches VERSION from
// the module proxy. A release tag is there. A source build's version is not: v0.15.1-dev+ffd872d
// was written into the Dockerfile and the image failed to build. @latest and @main are no fix,
// since both pin nothing and the image changes under a deployment nobody edited. So a
// non-release build refuses and says to name the release to pin.
func packPin(build, pin string) (string, error) {
	if pin != "" {
		if !agentbin.Release(pin) {
			return "", fmt.Errorf("--version %q is not a release: the packed image installs sbx "+
				"from the Go module proxy, which has only tags like v0.15.1 - see "+
				"https://github.com/aryanmehrotra/sbx/releases", pin)
		}

		return pin, nil
	}

	if agentbin.Release(build) {
		return build, nil
	}

	return "", fmt.Errorf("this sbx is a source build (%q), not a release, so there is no "+
		"published version for the packed image to install. Name the release to pin: "+
		"`sbx pack --version v0.15.1` (the list is at https://github.com/aryanmehrotra/sbx/releases)", build)
}

// pinNote is the comment above the install line. Read by whoever opens the generated Dockerfile
// and asks why it does not say @latest - a question worth answering where it is asked.
func pinNote(version string) string {
	return "# " + version + ` rather than @latest: a published release, so the image builds the
# same sbx every time. @latest drifts the day the next release lands, which is how a build that
# worked last week fails on a machine nobody touched. -X main.version stamps the version, which
# go install does not, or the packed sbx would call itself "dev" in every log line.`
}

// InspectImage reads an image's entrypoint and command, pulling it if it is not local.
//
// Read rather than assumed: every image starts differently, and a wrapper that invented a start
// line would work for postgres and be quietly wrong for the next thing somebody packed.
func InspectImage(docker func(args ...string) (string, error)) func(string) ([]string, []string, error) {
	return func(image string) ([]string, []string, error) {
		read := func() (string, error) {
			return docker("inspect", image, "--format", "{{json .Config.Entrypoint}}|{{json .Config.Cmd}}")
		}

		out, err := read()
		if err != nil {
			if _, perr := docker("pull", image); perr != nil {
				return nil, nil, perr
			}

			if out, err = read(); err != nil {
				return nil, nil, err
			}
		}

		entryText, cmdText, _ := strings.Cut(strings.TrimSpace(out), "|")

		var entry, cmd []string

		_ = json.Unmarshal([]byte(entryText), &entry)
		_ = json.Unmarshal([]byte(cmdText), &cmd)

		return entry, cmd, nil
	}
}
