#!/usr/bin/env bash
# Generate the Homebrew formula for a published release.
#
#   scripts/brew-formula.sh v0.1.0 > Formula/sbx.rb
#
# The checksums are read from the release's own SHA256SUMS rather than recomputed here, so the
# formula can only ever describe artefacts that were actually published. A formula whose
# checksums were pasted by hand is a formula that is one distraction away from being wrong,
# and the failure mode is a user seeing "SHA256 mismatch" and concluding they have been
# tampered with.
#
# The formula installs the prebuilt binary rather than building from source. Building would
# add a ~150 MB Go toolchain download to every install of a 6 MB binary that this project
# already publishes for the exact platform Homebrew is running on.
#
# freebsd and windows are published but have no Homebrew, so only the four macOS and Linux
# targets appear here.
set -euo pipefail

VERSION="${1:?usage: brew-formula.sh vX.Y.Z}"
REPO="${REPO:-aryanmehrotra/sbx}"
BASE="https://github.com/${REPO}/releases/download/${VERSION}"

sums=$(curl -fsSL "${BASE}/SHA256SUMS")

# sha <os> <arch> - fails loudly rather than emitting a formula with a blank checksum.
sha() {
  local want="sbx_${VERSION}_${1}_${2}" line
  line=$(printf '%s\n' "$sums" | awk -v f="$want" '$2 == f {print $1}')

  [ -n "$line" ] || { echo "brew-formula: no checksum for $want in $VERSION" >&2; exit 1; }

  printf '%s' "$line"
}

# Homebrew's `version` is bare, while the assets and the -X stamp carry the leading v.
bare="${VERSION#v}"

cat <<FORMULA
# Generated by scripts/brew-formula.sh in ${REPO}. Do not edit by hand:
# the checksums come from the release's own SHA256SUMS.
class Sbx < Formula
  desc "Per-branch sandboxes that sleep when nobody is using them"
  homepage "https://github.com/${REPO}"
  version "${bare}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/sbx_${VERSION}_darwin_arm64"
      sha256 "$(sha darwin arm64)"
    end

    on_intel do
      url "${BASE}/sbx_${VERSION}_darwin_amd64"
      sha256 "$(sha darwin amd64)"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/sbx_${VERSION}_linux_arm64"
      sha256 "$(sha linux arm64)"
    end

    on_intel do
      url "${BASE}/sbx_${VERSION}_linux_amd64"
      sha256 "$(sha linux amd64)"
    end
  end

  def install
    # The download is a bare binary, not an archive, so it arrives without an exec bit and
    # under its platform-specific name.
    binary = Dir["sbx_*"].first
    chmod 0755, binary
    bin.install binary => "sbx"
  end

  def caveats
    <<~EOS
      sbx needs its daemon running to hand out addresses:

        sbx serve --idle 5m &

      deploy/ in the repository has a launchd plist and a systemd unit, both running as you
      rather than as root. Check what this host can do with:

        sbx doctor
    EOS
  end

  test do
    # Two things worth failing on: the binary runs at all on this platform, and it is the
    # version the formula claims. A formula that installs the wrong release still passes a
    # test that only greps the help text.
    assert_match "v#{version}", shell_output("#{bin}/sbx --version")

    # 2>&1 because v0.1.0 printed --help to stderr. Fixed after that release, and merging the
    # streams here keeps this formula working against both.
    assert_match "sandboxes", shell_output("#{bin}/sbx --help 2>&1")
  end
end
FORMULA
