package provider

// The Kubernetes provider: the same sandboxes, somewhere they can outlive a laptop.
//
// Almost everything is a rename. `docker start` becomes scale-to-1, `docker stop` becomes
// scale-to-0, a HEALTHCHECK becomes a readinessProbe, a named volume becomes a PVC, and
// the rule that sleeping must never destroy storage is the same rule.
//
// The one thing that genuinely simplifies is addressing. Locally every sandbox shares one
// loopback, so services are remapped into a per-slot port block and the daemon has to hold
// a port that answers while nothing is behind it. Here every pod has its own address, so a
// sandbox's MySQL is reachable at its own name on 3306 and there is no remapping at all -
// which is why callers ask this package for an Endpoint rather than for a port.
//
// Manifests are emitted as JSON rather than YAML. kubectl accepts both, and JSON is
// generated by a library that already knows how to escape a health command containing
// quotes, whereas hand-indented YAML is one bad string away from a manifest that means
// something else.

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aryanmehrotra/sbx/internal/spec"
)

type kubeProvider struct {
	namespace string

	// The readiness command each deployment declares, cached with a short TTL.
	//
	// Cached because Probe is the body of the wake poll loop and this was a `kubectl get`
	// fork on every iteration, on top of the `kubectl exec` that follows it - and kubectl
	// startup dominates a cluster wake.
	//
	// TTL rather than explicit invalidation, which is what the first version got wrong.
	// Create does call forgetReady, but Create runs in the `sbx create` process while the
	// cache lives in the long-running `sbx serve` daemon - so the invalidation never reached
	// the process that actually probes. `sbx rm x && sbx create x` with an edited health
	// command would have left the daemon probing with the old one for weeks. Exactly the
	// mistake the docker docstring one file over describes: reasoning about invalidation
	// against something the cache cannot see.
	//
	// A few seconds collapses a 100 ms poll loop to one lookup per wake, which is the whole
	// point, and bounds staleness to a single wake, which is the whole safety.
	mu    sync.Mutex
	ready map[string]readyEntry
}

func newKube(namespace string) *kubeProvider {
	if namespace == "" {
		namespace = "sbx"
	}

	return &kubeProvider{namespace: namespace, ready: map[string]readyEntry{}}
}

// readyEntry is a cached readiness command and when it was read.
type readyEntry struct {
	command string
	at      time.Time
}

// readyTTL bounds how stale a cached readiness command can be: long enough that one wake's
// poll loop does a single lookup, short enough that a recreated deployment is picked up on
// the next wake rather than never.
const readyTTL = 5 * time.Second

// forgetReady drops a cached readiness command. Called wherever sbx changes a deployment,
// which is the only way the declared command can change.
func (k *kubeProvider) forgetReady(ref string) {
	k.mu.Lock()
	defer k.mu.Unlock()

	delete(k.ready, ref)
}

// cachedReady returns the readiness command, asking kubectl only once per deployment.
func (k *kubeProvider) cachedReady(ref string) (string, bool) {
	k.mu.Lock()
	e, seen := k.ready[ref]
	k.mu.Unlock()

	if seen && time.Since(e.at) < readyTTL {
		return e.command, e.command != ""
	}

	out, err := k.kc("", "get", "deployment", ref, "-o",
		"jsonpath={.spec.template.spec.containers[0].readinessProbe.exec.command[-1]}")
	if err != nil {
		// Not cached: an unreachable API server is not an answer about this deployment, and
		// remembering it as "no command" would make every later probe wrong.
		return "", false
	}

	cmd := strings.TrimSpace(out)

	k.mu.Lock()
	k.ready[ref] = readyEntry{command: cmd, at: time.Now()}
	k.mu.Unlock()

	return cmd, cmd != ""
}

func (k *kubeProvider) Name() string { return "kubernetes/" + k.namespace }

func kubectl(stdin string, args ...string) (string, error) {
	cmd := exec.Command("kubectl", args...)
	if stdin != "" {
		cmd.Stdin = strings.NewReader(stdin)
	}

	var out bytes.Buffer

	cmd.Stdout = &out
	cmd.Stderr = &out

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("kubectl %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(out.String()))
	}

	return strings.TrimSpace(out.String()), nil
}

func (k *kubeProvider) kc(stdin string, args ...string) (string, error) {
	return kubectl(stdin, append([]string{"-n", k.namespace}, args...)...)
}

// k8s names are DNS-1123 labels, which is stricter than a docker container name.
func kubeName(sandbox, service string) string {
	return strings.ToLower("sbx-" + sandbox + "-" + service)
}

// Endpoints: a service name and the port the workload actually listens on. No block, no
// backing port, no arithmetic - the constraint that produced those does not exist here.
func (k *kubeProvider) Endpoints(sandbox, service string, _, _ int, containerPorts []int) []Endpoint {
	eps := make([]Endpoint, 0, len(containerPorts))

	for _, p := range containerPorts {
		eps = append(eps, Endpoint{
			Host: fmt.Sprintf("%s.%s.svc.cluster.local", kubeName(sandbox, service), k.namespace),
			Port: p,
		})
	}

	return eps
}

// AllocSlot is a no-op: slots exist to divide a shared port space, and there isn't one.
func (k *kubeProvider) AllocSlot(context.Context, string) (int, error) { return 0, nil }

// activatorSelector is the label the activator's own pods carry. The client-facing Service
// points here, which is the whole trick: a connection can arrive, and be held, while the
// workload has zero replicas.
const activatorSelector = "sbx-activator"

// activatorPort is where the activator listens for one service. It multiplexes every
// sandbox onto one pod, so the per-slot block from the local provider earns its keep here
// too - but it is now entirely private, and no client ever sees it.
func activatorPort(slot, ordinal, i int) int {
	return publicBase + slot*blockSize + ordinal + i
}

func (k *kubeProvider) Create(ctx context.Context, sandbox string, slot, ordinal int, service string,
	svc spec.Service, _ []Endpoint, _ string, iso Isolation,
) error {
	// Refused, not ignored. The cluster answer is a NetworkPolicy, which needs a CNI that
	// enforces them - many do not - and silently leaving a service open when its spec said
	// deny is the one outcome a security control must never produce.
	if svc.Egress == spec.EgressDeny {
		return fmt.Errorf("service %q declares egress deny, which the kubernetes provider "+
			"does not implement yet: the cluster answer is a NetworkPolicy and it is only "+
			"enforced by some CNIs, so sbx will not pretend to have applied one", service)
	}

	// Refused rather than translated. A cluster's hostPath is a *node's* disk, not the laptop
	// the spec was written on, so mounting one would satisfy the manifest and give the service
	// a directory nobody asked for on a machine the author has never seen. The honest cluster
	// answers are a PVC for state that should persist and a ConfigMap for files that should be
	// read, and both are different enough to be written rather than guessed.
	if len(svc.Mounts) > 0 {
		return fmt.Errorf("service %q declares mounts, which the kubernetes provider does not "+
			"implement: a hostPath is a node's filesystem rather than yours, and mounting one "+
			"would look like it worked. Use `volume` for state that must persist, or `files` "+
			"for configuration", service)
	}

	name := kubeName(sandbox, service)

	if _, err := k.kc("", "get", "deployment", name); err == nil {
		fmt.Printf("  %-12s already exists\n", service)
		return nil
	}

	if _, err := kubectl("", "get", "namespace", k.namespace); err != nil {
		if _, err := kubectl("", "create", "namespace", k.namespace); err != nil {
			return err
		}
	}

	// Check the runtime exists before asking for it.
	//
	// Kubernetes already fails closed here - a pod naming an absent RuntimeClass is never
	// admitted, so nothing runs with weaker isolation than was asked for. But it fails
	// closed silently: the Deployment is created, no pod ever appears, and two minutes
	// later the error says the service never became ready. That sends someone looking at
	// their database while the actual problem is that the cluster has no gVisor.
	if rc := kubeRuntimeClass(iso); rc != "" {
		if _, err := kubectl("", "get", "runtimeclass", rc); err != nil {
			return fmt.Errorf("isolation %q needs RuntimeClass %q, which this cluster does not have - "+
				"install it, or create with --isolation container", iso, rc)
		}
	}

	labels := map[string]string{
		"app":              name,
		kubeLabelSandbox:   sandbox,
		kubeLabelService:   service,
		kubeLabelSlot:      strconv.Itoa(slot),
		kubeLabelOrdinal:   strconv.Itoa(ordinal),
		kubeLabelManagedBy: "sbx",
	}

	if svc.Volume != "" {
		if err := k.applyJSON(k.pvc(name, labels)); err != nil {
			return err
		}
	}

	k.forgetReady(name)

	if err := k.applyJSON(k.deployment(name, labels, svc, iso)); err != nil {
		return err
	}

	// Two Services, and the split is the point.
	//
	// The one clients use selects the *activator*, so a connection to a sleeping sandbox
	// still lands somewhere that can answer - which is exactly what a Service selecting the
	// workload cannot do at zero replicas. The activator then scales the workload up and
	// forwards through the second Service, which does select the workload.
	//
	// Knative solves the same problem by moving its activator in and out of the data path.
	// Staying in path costs one in-cluster hop and buys byte-level idle detection with the
	// identical policy the local daemon already runs.
	if err := k.applyJSON(k.clientService(name, labels, svc, slot, ordinal)); err != nil {
		return err
	}

	return k.applyJSON(k.workloadService(name, labels, svc))
}

func (k *kubeProvider) applyJSON(obj map[string]any) error {
	body, err := json.Marshal(obj)
	if err != nil {
		return err
	}

	_, err = k.kc(string(body), "apply", "-f", "-")

	return err
}

func (k *kubeProvider) pvc(name string, labels map[string]string) map[string]any {
	return map[string]any{
		"apiVersion": "v1",
		"kind":       "PersistentVolumeClaim",
		"metadata":   map[string]any{"name": name, "labels": labels},
		"spec": map[string]any{
			"accessModes": []string{"ReadWriteOnce"},
			"resources":   map[string]any{"requests": map[string]any{"storage": "2Gi"}},
		},
	}
}

func (k *kubeProvider) deployment(name string, labels map[string]string, svc spec.Service, iso Isolation) map[string]any {
	container := map[string]any{
		"name":  "app",
		"image": svc.Image,
	}

	if len(svc.Args) > 0 {
		container["args"] = svc.Args
	}

	var ports []any
	for _, p := range svc.Ports {
		ports = append(ports, map[string]any{"containerPort": p})
	}

	container["ports"] = ports

	var env []any

	for _, key := range SortedKeys(svc.Env) {
		env = append(env, map[string]any{"name": key, "value": svc.Env[key]})
	}

	if len(env) > 0 {
		container["env"] = env
	}

	// The healthcheck becomes a readiness probe, which is the same promise in the same
	// place: nothing routes to this pod until it says it is serving. failureThreshold is
	// generous for the same reason the local start period is - a database opening its data
	// directory is not a broken database.
	if svc.Health != "" {
		// Kubernetes counts probe periods in whole seconds, so a sub-second interval becomes
		// one second rather than zero - zero means "use the default" to the API server, which
		// is ten, and a spec asking for a faster probe would have got a slower one.
		period := int(probeInterval(svc).Round(time.Second) / time.Second)
		if period < 1 {
			period = 1
		}

		container["readinessProbe"] = map[string]any{
			"exec":                map[string]any{"command": []string{"sh", "-c", svc.Health}},
			"periodSeconds":       period,
			"timeoutSeconds":      2,
			"failureThreshold":    60,
			"initialDelaySeconds": 1,
		}
	}

	if svc.Volume != "" {
		container["volumeMounts"] = []any{map[string]any{"name": "data", "mountPath": svc.Volume}}
	}

	// A cluster expresses this as limits on the container. Requests are deliberately left
	// alone: setting them would change how the scheduler places a sandbox, which is the
	// cluster operator's business, not ours.
	if svc.CPU != "" || svc.Memory != "" {
		limits := map[string]any{}
		if svc.CPU != "" {
			limits["cpu"] = svc.CPU
		}

		if svc.Memory != "" {
			limits["memory"] = svc.Memory
		}

		container["resources"] = map[string]any{"limits": limits}
	}

	podSpec := map[string]any{"containers": []any{container}}

	if svc.Volume != "" {
		podSpec["volumes"] = []any{map[string]any{
			"name":                  "data",
			"persistentVolumeClaim": map[string]any{"claimName": name},
		}}
	}

	// Where the isolation tier actually lands. A cluster that has not installed the runtime
	// will refuse the pod, which is the correct failure: silently running a sandbox with
	// weaker isolation than was asked for is how a shared cluster gets a bad afternoon.
	if rc := kubeRuntimeClass(iso); rc != "" {
		podSpec["runtimeClassName"] = rc
	}

	return map[string]any{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"metadata":   map[string]any{"name": name, "labels": labels},
		"spec": map[string]any{
			"replicas": 1,
			"selector": map[string]any{"matchLabels": map[string]string{"app": name}},
			"template": map[string]any{
				"metadata": map[string]any{"labels": labels},
				"spec":     podSpec,
			},
		},
	}
}

// clientService keeps the natural address - mysql on :3306 - and sends it to the activator.
func (k *kubeProvider) clientService(name string, labels map[string]string, svc spec.Service, slot, ordinal int) map[string]any {
	var ports []any

	for i, p := range svc.Ports {
		ports = append(ports, map[string]any{
			"name":       fmt.Sprintf("p%d", p),
			"port":       p,
			"targetPort": activatorPort(slot, ordinal, i),
		})
	}

	return map[string]any{
		"apiVersion": "v1",
		"kind":       "Service",
		"metadata":   map[string]any{"name": name, "labels": labels},
		"spec": map[string]any{
			"selector": map[string]string{"app": activatorSelector},
			"ports":    ports,
		},
	}
}

// workloadService is what the activator forwards to once the pods are up. Internal only.
func (k *kubeProvider) workloadService(name string, labels map[string]string, svc spec.Service) map[string]any {
	var ports []any

	for _, p := range svc.Ports {
		ports = append(ports, map[string]any{
			"name":       fmt.Sprintf("p%d", p),
			"port":       p,
			"targetPort": p,
		})
	}

	return map[string]any{
		"apiVersion": "v1",
		"kind":       "Service",
		"metadata":   map[string]any{"name": name + "-app", "labels": labels},
		"spec": map[string]any{
			"selector": map[string]string{"app": name},
			"ports":    ports,
		},
	}
}

func kubeRuntimeClass(iso Isolation) string {
	switch iso {
	case IsolationGVisor:
		return "gvisor"
	case IsolationKata:
		return "kata"
	default:
		return ""
	}
}

func (k *kubeProvider) Start(_ context.Context, ref string) error {
	_, err := k.kc("", "scale", "deployment", ref, "--replicas=1")
	return err
}

func (k *kubeProvider) Stop(_ context.Context, ref string) error {
	_, err := k.kc("", "scale", "deployment", ref, "--replicas=0")
	return err
}

// Healthy asks the deployment how many replicas are ready. That number is downstream of
// the readiness probe, so it means the same thing docker's health status does.
func (k *kubeProvider) Healthy(_ context.Context, ref string) (bool, bool) {
	probe, err := k.kc("", "get", "deployment", ref, "-o",
		"jsonpath={.spec.template.spec.containers[0].readinessProbe}")
	if err != nil {
		return false, false
	}

	declared := strings.TrimSpace(probe) != ""

	ready, err := k.kc("", "get", "deployment", ref, "-o", "jsonpath={.status.readyReplicas}")
	if err != nil {
		return false, declared
	}

	n, _ := strconv.Atoi(strings.TrimSpace(ready))

	return n >= 1, declared
}

// Probe runs the readiness command in the pod now, for the same reason the docker provider
// does: on the wake path the caller is holding a connection, and readiness republished on a
// probe interval is slower than asking.
func (k *kubeProvider) Probe(ctx context.Context, ref string) (bool, bool) {
	cmd, ok := k.cachedReady(ref)
	if !ok {
		return false, false
	}

	if _, err := k.Exec(ctx, ref, []string{"sh", "-c", cmd}); err != nil {
		return false, true
	}

	return true, true
}

func (k *kubeProvider) ExecTTY(ctx context.Context, ref string, argv []string) error {
	args := []string{"exec", "-i"}
	if isTerminal(os.Stdin) {
		args = append(args, "-t")
	}

	args = append(args, "-n", k.namespace, ref, "--")
	args = append(args, argv...)

	cmd := exec.CommandContext(ctx, "kubectl", args...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr

	return cmd.Run()
}

func (k *kubeProvider) Exec(_ context.Context, ref string, argv []string) (string, error) {
	return k.kc("", append([]string{"exec", "deployment/" + ref, "--"}, argv...)...)
}

func (k *kubeProvider) Logs(ctx context.Context, ref string, lines int, follow bool, w io.Writer) error {
	args := []string{"-n", k.namespace, "logs", "deployment/" + ref, "--tail", strconv.Itoa(lines)}
	if follow {
		args = append(args, "--follow")
	}

	cmd := exec.CommandContext(ctx, "kubectl", args...)
	cmd.Stdout = w
	cmd.Stderr = w

	err := cmd.Run()
	if ctx.Err() != nil {
		return nil
	}

	return err
}

func (k *kubeProvider) Copy(_ context.Context, ref, src, dst string) error {
	pod, err := k.kc("", "get", "pod", "-l", "app="+ref, "-o", "jsonpath={.items[0].metadata.name}")
	if err != nil || pod == "" {
		return fmt.Errorf("no running pod for %s - copy needs it awake", ref)
	}

	_, err = k.kc("", "cp", qualify(pod, src), qualify(pod, dst))

	return err
}

func (k *kubeProvider) List(_ context.Context, sandbox string) ([]Unit, error) {
	sel := kubeLabelManagedBy + "=sbx"
	if sandbox != "" {
		sel += "," + kubeLabelSandbox + "=" + sandbox
	}

	out, err := k.kc("", "get", "deployments", "-l", sel, "-o", "json")
	if err != nil {
		// Same rule as the docker provider: a cluster we cannot reach is an error, not an
		// empty namespace. The activator logs it and retries rather than concluding every
		// sandbox vanished and closing its listeners.
		return nil, fmt.Errorf("listing sandboxes in %s: %w", k.namespace, err)
	}

	var list struct {
		Items []struct {
			Metadata struct {
				Name   string            `json:"name"`
				Labels map[string]string `json:"labels"`
			} `json:"metadata"`
			Spec struct {
				Replicas int `json:"replicas"`
				Template struct {
					Spec struct {
						Containers []struct {
							Ports []struct {
								ContainerPort int `json:"containerPort"`
							} `json:"ports"`
						} `json:"containers"`
					} `json:"spec"`
				} `json:"template"`
			} `json:"spec"`
			Status struct {
				ReadyReplicas int `json:"readyReplicas"`
			} `json:"status"`
		} `json:"items"`
	}

	if err := json.Unmarshal([]byte(out), &list); err != nil {
		return nil, err
	}

	var units []Unit

	for _, it := range list.Items {
		slot, _ := strconv.Atoi(it.Metadata.Labels[kubeLabelSlot])

		u := Unit{
			Sandbox: it.Metadata.Labels[kubeLabelSandbox],
			Service: it.Metadata.Labels[kubeLabelService],
			Slot:    slot,
			Ref:     it.Metadata.Name,
			Running: it.Spec.Replicas > 0,
		}

		ordinal, _ := strconv.Atoi(it.Metadata.Labels[kubeLabelOrdinal])

		if len(it.Spec.Template.Spec.Containers) > 0 {
			for i, p := range it.Spec.Template.Spec.Containers[0].Ports {
				u.Client = append(u.Client, Endpoint{
					Host: fmt.Sprintf("%s.%s.svc.cluster.local", it.Metadata.Name, k.namespace),
					Port: p.ContainerPort,
				})

				u.Listen = append(u.Listen, activatorPort(slot, ordinal, i))

				u.Upstream = append(u.Upstream, Endpoint{
					Host: fmt.Sprintf("%s-app.%s.svc.cluster.local", it.Metadata.Name, k.namespace),
					Port: p.ContainerPort,
				})
			}
		}

		units = append(units, u)
	}

	return units, nil
}

func (k *kubeProvider) Remove(_ context.Context, sandbox string) error {
	sel := kubeLabelManagedBy + "=sbx," + kubeLabelSandbox + "=" + sandbox

	out, err := k.kc("", "get", "deployments", "-l", sel, "-o", "name")
	if err != nil || strings.TrimSpace(out) == "" {
		return fmt.Errorf("no sandbox %q in namespace %s", sandbox, k.namespace)
	}

	// PVCs are deleted here and nowhere else. Sleeping a sandbox must never reach this
	// path - that is the whole reason a stopped sandbox is still a sandbox.
	// Both Services carry the labels, so one delete per kind still gets the pair.
	for _, kind := range []string{"deployment", "service", "pvc"} {
		if _, err := k.kc("", "delete", kind, "-l", sel); err != nil {
			return err
		}
	}

	fmt.Printf("  removed %s from namespace %s\n", sandbox, k.namespace)

	return nil
}
